import { TooltipProvider } from "@/components/ui/tooltip";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import "./globals.css";
import React from "react";
import AppWalletProvider from "@/components/ui/AppWalletProvider";
import Navbar from "@/layout/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
      <html lang="en" className="h-full">
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 min-h-screen`}
      >
      <AppWalletProvider>
          <div className="relative">
              {/* sticky not working */}
              <Navbar/>
              <div className={`pt-24`}>
                  <Toaster richColors closeButton position="top-right"/>
                  <TooltipProvider>{children}</TooltipProvider>
              </div>
          </div>
      </AppWalletProvider>
      </body>
      </html>
  );
}
