import { ThemeProvider } from "@/components/theme/theme-context";
import AppWalletProvider from "@/components/ui/app-wallet-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import Navbar from "@/layout/navbar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import React from "react";
import { Toaster } from "sonner";
import "./globals.css";
import Footer from "@/layout/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-gray-100 antialiased`}
      >
        <ThemeProvider>
          <AppWalletProvider>
            <div className="relative">
              {/* sticky not working */}
              <Navbar />
              <Toaster richColors closeButton position="top-right" />
              <div className={`pt-16 pb-16`}>
                <TooltipProvider>{children}</TooltipProvider>
              </div>
              <Footer />
            </div>
          </AppWalletProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
